### ISSUE TITLE
devel package depends on python2

### ISSUE THREAD

**Issue by rokm** [negativo17/cuda-cudnn#1]
```cuda-cudnn-devel package``` is pulling in ```python2``` package on an otherwise python2-free Fedora 31 installation.

This is because some of the packages samples are written in python, and the .spec file [explicitly changes their shebang from python to python2](https://github.com/negativo17/cuda-cudnn/blob/3be5a6009369495c8fbbd7083a4b665fc52f7a9d/cuda-cudnn.spec#L44).

While the samples should probably be ported to python3, they are not core part of the package but rather documentation, and as such should not cause dependency on python at all. This can be fixed by [filtering requires after scanning](https://docs.fedoraproject.org/en-US/packaging-guidelines/AutoProvidesAndRequiresFiltering/#_filtering_provides_and_requires_after_scanning), i.e.:
```
%global __requires_exclude ^/usr/bin/python2$
```

**Comment by scaronni** [comment]
Thanks for spotting. I will probably move them to a samples subpackage.

**Comment by scaronni** [comment]
New build with split samples online soon.

**Comment by rokm** [comment]
Cool, thanks!
